"""made some values nullable

Revision ID: 1e2cd5cc343c
Revises: 7d20c50407e7
Create Date: 2026-09-14 01:37:19.734520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2cd5cc343c'
down_revision: Union[str, Sequence[str], None] = '7d20c50407e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixtures', 'home_coach_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fixtures', 'away_coach_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fixtures', 'referee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixtures', 'referee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fixtures', 'away_coach_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fixtures', 'home_coach_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
