"""Add player_stats table

Revision ID: 28ad80a82bde
Revises: b32fea35025a
Create Date: 2026-09-27 22:15:03.094916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ad80a82bde'
down_revision: Union[str, Sequence[str], None] = 'b32fea35025a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('stat_type', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('player_position', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season_id', 'stat_type', 'player_id', name='uq_player_stats_league_season_stat_player')
    )
    op.create_index(op.f('ix_player_stats_league_id'), 'player_stats', ['league_id'], unique=False)
    op.create_index(op.f('ix_player_stats_season_id'), 'player_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_player_stats_stat_type'), 'player_stats', ['stat_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_stat_type'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_season_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_league_id'), table_name='player_stats')
    op.drop_table('player_stats')
    # ### end Alembic commands ###
