"""add unique constraint on comp_stages league_id stage

Revision ID: 5ee3e7bcd4d4
Revises: 5202a145abb9
Create Date: 2026-09-16 02:12:41.871066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee3e7bcd4d4'
down_revision: Union[str, Sequence[str], None] = '5202a145abb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_comp_stages_league_id_stage', 'comp_stages', ['league_id', 'stage'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_comp_stages_league_id_stage', 'comp_stages', type_='unique')
    # ### end Alembic commands ###
