"""new table created for live fixtures

Revision ID: 6c8c667b400e
Revises: a2852a2acb72
Create Date: 2026-09-07 12:42:15.567996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c8c667b400e'
down_revision: Union[str, Sequence[str], None] = 'a2852a2acb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_fixtures',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('current_minute', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_score_ht', sa.Integer(), nullable=False),
    sa.Column('away_score_ht', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_live_fixtures_league_id'), 'live_fixtures', ['league_id'], unique=False)
    op.drop_column('fixtures', 'attendance')
    op.drop_column('fixtures', 'status')
    op.drop_column('fixtures', 'last_updated')
    op.drop_column('fixtures', 'current_minute')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('current_minute', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fixtures', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('fixtures', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('fixtures', sa.Column('attendance', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_live_fixtures_league_id'), table_name='live_fixtures')
    op.drop_table('live_fixtures')
    # ### end Alembic commands ###
