"""add round and stage data

Revision ID: 7d20c50407e7
Revises: 9d2400d95daa
Create Date: 2026-09-14 01:07:42.856751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d20c50407e7'
down_revision: Union[str, Sequence[str], None] = '9d2400d95daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted: match_id's primary key
    # constraint is dropped along with the column, so it must be recreated on
    # the new `id` column explicitly, autogenerate does not do this for you. ###
    op.drop_constraint('fixtures_pkey', 'fixtures', type_='primary')
    op.add_column('fixtures', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('fixtures', sa.Column('home_coach_id', sa.Integer(), nullable=False))
    op.add_column('fixtures', sa.Column('away_coach_id', sa.Integer(), nullable=False))
    op.add_column('fixtures', sa.Column('referee_id', sa.Integer(), nullable=False))
    op.add_column('fixtures', sa.Column('round_number', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('round_name', sa.String(), nullable=True))
    op.add_column('fixtures', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('fixtures', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('fixtures', sa.Column('stage_name', sa.String(), nullable=True))
    op.drop_column('fixtures', 'match_id')
    op.create_primary_key('fixtures_pkey', 'fixtures', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fixtures_pkey', 'fixtures', type_='primary')
    op.add_column('fixtures', sa.Column('match_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('fixtures', 'stage_name')
    op.drop_column('fixtures', 'stage')
    op.drop_column('fixtures', 'group_name')
    op.drop_column('fixtures', 'round_name')
    op.drop_column('fixtures', 'round_number')
    op.drop_column('fixtures', 'referee_id')
    op.drop_column('fixtures', 'away_coach_id')
    op.drop_column('fixtures', 'home_coach_id')
    op.drop_column('fixtures', 'id')
    op.create_primary_key('fixtures_pkey', 'fixtures', ['match_id'])
    # ### end Alembic commands ###
