"""consolidate fixture tables

Revision ID: 9d2400d95daa
Revises: 4f33613fd45b
Create Date: 2026-09-07 13:36:09.837098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d2400d95daa'
down_revision: Union[str, Sequence[str], None] = '4f33613fd45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_fixtures_league_id'), table_name='live_fixtures')
    op.drop_table('live_fixtures')
    op.add_column('fixtures', sa.Column('status', sa.String(), nullable=False))
    op.add_column('fixtures', sa.Column('current_minute', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('home_score_ht', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('away_score_ht', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('fixtures', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fixtures', 'home_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fixtures', 'away_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_fixtures_status'), 'fixtures', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixtures_status'), table_name='fixtures')
    op.alter_column('fixtures', 'away_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fixtures', 'home_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fixtures', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('fixtures', 'last_updated')
    op.drop_column('fixtures', 'away_score_ht')
    op.drop_column('fixtures', 'home_score_ht')
    op.drop_column('fixtures', 'current_minute')
    op.drop_column('fixtures', 'status')
    op.create_table('live_fixtures',
    sa.Column('match_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_team', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_team', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_minute', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_score_ht', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_score_ht', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('match_id', name=op.f('live_fixtures_pkey'))
    )
    op.create_index(op.f('ix_live_fixtures_league_id'), 'live_fixtures', ['league_id'], unique=False)
    # ### end Alembic commands ###
