"""added season id column to stages table

Revision ID: ac2b8932aa3a
Revises: 5ee3e7bcd4d4
Create Date: 2026-09-26 23:28:05.990437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2b8932aa3a'
down_revision: Union[str, Sequence[str], None] = '5ee3e7bcd4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comp_stages', sa.Column('season_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_comp_stages_season_id'), 'comp_stages', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comp_stages_season_id'), table_name='comp_stages')
    op.drop_column('comp_stages', 'season_id')
    # ### end Alembic commands ###
