"""Update standings table

Revision ID: b32fea35025a
Revises: b8d46354485d
Create Date: 2026-09-27 01:11:24.189882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32fea35025a'
down_revision: Union[str, Sequence[str], None] = 'b8d46354485d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standings', sa.Column('gf', sa.Integer(), nullable=False))
    op.add_column('standings', sa.Column('ga', sa.Integer(), nullable=False))
    op.add_column('standings', sa.Column('gd', sa.Integer(), nullable=False))
    op.add_column('standings', sa.Column('pts', sa.Integer(), nullable=False))
    op.add_column('standings', sa.Column('xgf', sa.Float(), nullable=True))
    op.add_column('standings', sa.Column('xga', sa.Float(), nullable=True))
    op.add_column('standings', sa.Column('xgd', sa.Float(), nullable=True))
    op.create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    op.drop_column('standings', 'xg_for')
    op.drop_column('standings', 'xg_diff')
    op.drop_column('standings', 'goals_against')
    op.drop_column('standings', 'points')
    op.drop_column('standings', 'goal_diff')
    op.drop_column('standings', 'goals_for')
    op.drop_column('standings', 'xg_against')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standings', sa.Column('xg_against', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('standings', sa.Column('goals_for', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('standings', sa.Column('goal_diff', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('standings', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('standings', sa.Column('goals_against', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('standings', sa.Column('xg_diff', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('standings', sa.Column('xg_for', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_standings_team_id'), table_name='standings')
    op.drop_column('standings', 'xgd')
    op.drop_column('standings', 'xga')
    op.drop_column('standings', 'xgf')
    op.drop_column('standings', 'pts')
    op.drop_column('standings', 'gd')
    op.drop_column('standings', 'ga')
    op.drop_column('standings', 'gf')
    # ### end Alembic commands ###
