"""Created standings table

Revision ID: b8d46354485d
Revises: ac2b8932aa3a
Create Date: 2026-09-27 00:13:48.885093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d46354485d'
down_revision: Union[str, Sequence[str], None] = 'ac2b8932aa3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_diff', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('xg_for', sa.Float(), nullable=True),
    sa.Column('xg_against', sa.Float(), nullable=True),
    sa.Column('xg_diff', sa.Float(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('zone_key', sa.String(), nullable=True),
    sa.Column('zone_label', sa.String(), nullable=True),
    sa.Column('zone_type', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season_id', 'team_id', name='uq_standings_league_season_team')
    )
    op.create_index(op.f('ix_standings_league_id'), 'standings', ['league_id'], unique=False)
    op.create_index(op.f('ix_standings_season_id'), 'standings', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standings_season_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_league_id'), table_name='standings')
    op.drop_table('standings')
    # ### end Alembic commands ###
